export my_top_dir=`pwd`

export PATH=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin:$PATH

mkdir -p out/host/linux-x86/bin
mkdir -p out/target/product/doom_row/obj/KERNEL_OBJ
mkdir -p out/target/product/doom_row/obj/kernel/msm-5.4/staging
cp -rdP $my_top_dir/prebuilts/bin/dtc $my_top_dir/out/host/linux-x86/bin/
cp -rdP $my_top_dir/prebuilts/bin/ufdt_apply_overlay $my_top_dir/out/host/linux-x86/bin/
cp -rdP $my_top_dir/prebuilts/staging/* $my_top_dir/out/target/product/doom_row/obj/kernel/msm-5.4/staging/

make -C kernel/msm-5.4 -j16 O=$my_top_dir/out/target/product/doom_row/obj/kernel/msm-5.4 REAL_CC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- AR=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-ar LLVM_NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm LD=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/ld.lld NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm DTC_EXT=$my_top_dir/out/host/linux-x86/bin/dtc DTC_OVERLAY_TEST_EXT=$my_top_dir/out/host/linux-x86/bin/ufdt_apply_overlay CONFIG_BUILD_ARM64_DT_OVERLAY=y HOSTCC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902b/bin/clang HOSTAR=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ar HOSTLD=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ld 'HOSTCFLAGS=-I${my_top_dir}/kernel/msm-5.4/include/uapi -I/usr/include -I/usr/include/x86_64-linux-gnu -I${my_top_dir}/kernel/msm-5.4/include' ARCH=arm64 CROSS_COMPILE=$my_top_dir/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- nethunter_defconfig 

 cat $my_top_dir/kernel/msm-5.4/arch/arm64/configs/oem/doom.config >> $my_top_dir/out/target/product/doom_row/obj/KERNEL_OBJ/.config 

 make -C kernel/msm-5.4 -j16 O=$my_top_dir/out/target/product/doom_row/obj/kernel/msm-5.4 REAL_CC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- AR=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-ar LLVM_NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm LD=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/ld.lld NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm DTC_EXT=$my_top_dir/out/host/linux-x86/bin/dtc DTC_OVERLAY_TEST_EXT=$my_top_dir/out/host/linux-x86/bin/ufdt_apply_overlay CONFIG_BUILD_ARM64_DT_OVERLAY=y HOSTCC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902b/bin/clang HOSTAR=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ar HOSTLD=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ld 'HOSTCFLAGS=-I${my_top_dir}/kernel/msm-5.4/include/uapi -I/usr/include -I/usr/include/x86_64-linux-gnu -I${my_top_dir}/kernel/msm-5.4/include' ARCH=arm64 CROSS_COMPILE=$my_top_dir/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- oldconfig 

 make -C kernel/msm-5.4 -j16 O=$my_top_dir/out/target/product/doom_row/obj/kernel/msm-5.4 REAL_CC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- AR=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-ar LLVM_NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm LD=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/ld.lld NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm DTC_EXT=$my_top_dir/out/host/linux-x86/bin/dtc DTC_OVERLAY_TEST_EXT=$my_top_dir/out/host/linux-x86/bin/ufdt_apply_overlay CONFIG_BUILD_ARM64_DT_OVERLAY=y HOSTCC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902b/bin/clang HOSTAR=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ar HOSTLD=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ld 'HOSTCFLAGS=-I${my_top_dir}/kernel/msm-5.4/include/uapi -I/usr/include -I/usr/include/x86_64-linux-gnu -I${my_top_dir}/kernel/msm-5.4/include' ARCH=arm64 CROSS_COMPILE=$my_top_dir/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- 

 make -C kernel/msm-5.4 -j16 O=$my_top_dir/out/target/product/doom_row/obj/kernel/msm-5.4 REAL_CC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- AR=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-ar LLVM_NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm LD=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/ld.lld NM=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902/bin/llvm-nm DTC_EXT=$my_top_dir/out/host/linux-x86/bin/dtc DTC_OVERLAY_TEST_EXT=$my_top_dir/out/host/linux-x86/bin/ufdt_apply_overlay CONFIG_BUILD_ARM64_DT_OVERLAY=y HOSTCC=$my_top_dir/prebuilts/clang/host/linux-x86/clang-r383902b/bin/clang HOSTAR=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ar HOSTLD=$my_top_dir/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-ld 'HOSTCFLAGS=-I${my_top_dir}/kernel/msm-5.4/include/uapi -I/usr/include -I/usr/include/x86_64-linux-gnu -I${my_top_dir}/kernel/msm-5.4/include' ARCH=arm64 CROSS_COMPILE=$my_top_dir/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- INSTALL_MOD_PATH=$my_top_dir/out/target/product/doom_row/obj/kernel/msm-5.4/staging INSTALL_MOD_STRIP=1 modules_install
